trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: create-pipelines.yaml
  parameters:
    repository: EU-Innovation-GetSubscriptionKey
    project: EU-Services
    storageAccountName: 'xzeentfstatessta000'
    storageAccountRG: 'XZE-E-N-UCDSEC-S-RGP-10'
    containerName: 'adopipelines'
    pipeline_location: EU-Infrastructure
