trigger:
  - main

variables:
  repositories:
    [
      {
        "repository": "EU-Innovation-GetSubscriptionKey",
        "project": "EU-Services"
      }
    ]

extends:
  template: create-pipelines.yaml  # Template is in the root directory
  parameters:
    repositories: ${{ variables.repositories }} 