trigger: none

parameters:
  - name: repository_name
    type: string
  - name: project_name
    type: string
    default: EU-Services

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: create-pipelines.yaml
  parameters:
    repository: ${{parameters.repository_name}}
    project: ${{parameters.project_name}}
    storageAccountName: 'xzeentfstatessta000'
    storageAccountRG: 'XZE-E-N-UCDSEC-S-RGP-10'
    containerName: 'adopipelines'
    pipeline_location: EU-Infrastructure
